#this document was provided by Pablo camarillo, but ive analyzed it and understood it.
version: "3"
services:
  spark-master:
    image: spark-master:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./notebooks:/opt/spark/work-dir
       - ./data:/opt/spark/work-dir/data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - PYTHONPATH=/opt/spark/work-dir/lib
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2 #modified this from 1
      - SPARK_WORKER_MEMORY=4G #modified this from 1
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
      - PYTHONPATH=/opt/spark/work-dir/lib
    volumes:
       - ./notebooks:/opt/spark/work-dir
       - ./data:/opt/spark/work-dir/data
  spark-notebook:
    image: jupyter-notebook:latest
    depends_on:
      - spark-worker
    environment:
      - PYTHONPATH=/opt/spark/work-dir/lib
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
       - ./notebooks:/opt/spark/work-dir
       - ./data:/opt/spark/work-dir/data
